# Generated by Django 3.0.5 on 2020-04-25 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scraperecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperecord',
            name='finish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scraperecord',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
